name: meet_me
description: "A new Flutter project."
publish_to: 'none' 


version: 1.0.0+1

environment:
  sdk: ^3.5.2

dependencies:
  flutter:
    sdk: flutter

  firebase_core: ^3.11.0
  firebase_auth: ^5.4.0
  agora_rtc_engine: ^6.5.0
  connectivity_plus: ^6.1.3
  equatable: ^2.0.7
  dartz: ^0.10.1
  cupertino_icons: ^1.0.8
  audioplayers: ^6.1.2
  permission_handler: ^11.3.1
  shared_preferences: ^2.5.2
  flutter_dotenv: ^5.2.1
  flutter_local_notifications: ^18.0.1
  cloud_firestore: ^5.6.3
  flutter_bloc: ^9.0.0
  get_it: ^8.0.3

dev_dependencies:
  flutter_test:
    sdk: flutter


  flutter_lints: ^4.0.0


flutter_icons:
  android: true
  ios: true
  web: true
  image_path: "assets/icons/launcher.png"

# For information on the generic Dart part of this file, see the
# following page: https://dart.dev/tools/pub/pubspec

# The following section is specific to Flutter.
flutter:

  # The following line ensures that the Material Icons font is
  # included with your application, so that you can use the icons in
  # the material Icons class.
  uses-material-design: true

  # To add assets to your application, add an assets section, like this:
  assets:
    - .env
    - assets/
    - assets/sound/