// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyDc5ZwjSvFKnFemx9Qj1kDa6pN4D4sTLpo',
    appId: '1:5968190042:web:429c6b7ff65008302e9663',
    messagingSenderId: '5968190042',
    projectId: 'meetme-47779',
    authDomain: 'meetme-47779.firebaseapp.com',
    storageBucket: 'meetme-47779.firebasestorage.app',
    measurementId: 'G-D91DD4500D',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyC2e533zIGhB5LWYj2tJsL207d-VdhVtwg',
    appId: '1:5968190042:android:f009a914a7e2f2482e9663',
    messagingSenderId: '5968190042',
    projectId: 'meetme-47779',
    storageBucket: 'meetme-47779.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyBGfpfmLa25aC44KnlI6Qt5M9i45Si-7Y0',
    appId: '1:5968190042:ios:0b7e7f28467649132e9663',
    messagingSenderId: '5968190042',
    projectId: 'meetme-47779',
    storageBucket: 'meetme-47779.firebasestorage.app',
    iosBundleId: 'com.example.meetMe',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyBGfpfmLa25aC44KnlI6Qt5M9i45Si-7Y0',
    appId: '1:5968190042:ios:0b7e7f28467649132e9663',
    messagingSenderId: '5968190042',
    projectId: 'meetme-47779',
    storageBucket: 'meetme-47779.firebasestorage.app',
    iosBundleId: 'com.example.meetMe',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyDc5ZwjSvFKnFemx9Qj1kDa6pN4D4sTLpo',
    appId: '1:5968190042:web:7eed90e2ed1bc1672e9663',
    messagingSenderId: '5968190042',
    projectId: 'meetme-47779',
    authDomain: 'meetme-47779.firebaseapp.com',
    storageBucket: 'meetme-47779.firebasestorage.app',
    measurementId: 'G-4BSTVEW5X2',
  );
}
